### ISSUE TITLE
не загружает при запуске проги события в лист событий

### ISSUE THREAD

**Issue by vebster123** [ragozin-n/datao#10]
делал я загрузку событий в форму, но они почему то не отображаются, опять же посмотрел как ты загружаешь из таблицы события, а он ни одного не добавляет обрабатывается эксепшн

**Comment by ragozin-n** [comment]
Fixed in https://github.com/ragozin-n/datao/commit/39b1130581b17a7cfb2189f550b2b5af5b4dee63
