### ISSUE TITLE
удаление события

### ISSUE THREAD

**Issue by vebster123** [ragozin-n/datao#9]
Добавить метод удаления, который принимает дату, время начала, имя мастера
нужен именно такой метод

**Comment by ragozin-n** [comment]
Вместо имени мастера, будет использовано ID мастера, так как в событии содержится только ссылка по ID

**Comment by ragozin-n** [comment]
Fixed in https://github.com/ragozin-n/datao/commit/01368cd4dacce716106224735b714ed186b5c815
